   
- user: name=gregf state=present uid=1000 shell=/usr/bin/zsh group=gregf groups=admin append=yes

- authorized_key: user=gregf key="{{ lookup('file', '/home/gregf/.ssh/id_rsa.pub') }}"

### SUDOERS

- lineinfile: dest=/etc/sudoers state=absent regexp="^%wheel"
- lineinfile: dest=/etc/sudoers state=absent regexp="^gregf"

### FIREWALLD (PUBLIC ZONE)

- name: ensure firewalld is started
  service: name=firewalld state=started enabled=yes

- name: configure firewall services / ports
  firewalld: service=ssh permanent=true state=enabled
  firewalld: service=http permanent=true state=enabled
  firewalld: service=https permanent=true state=enabled
  firewalld: port=8080/tcp permanent=true state=enabled # need to apply only to byrd, but applied generically for now
  firewalld: port=8090/tcp permanent=true state=enabled # need to apply only to byrd, but applied generically for now

- name: configure ssh hitcount / ban directives
  script: firewall.sh

- name: reload changes to firewalld
  service: name=firewalld state=restarted

