
- name: disable that pesky selinux
  selinux: state=disabled

- name: clean up sudoers
  lineinfile: dest=/etc/sudoers state=absent regexp="^%wheel"

- name: ensure firewalld is started
  service: name=firewalld state=started enabled=yes

- name: configure firewall services / ports
  firewalld: service=ssh permanent=true state=enabled
  register: sshd_ports

- name: reload changes to firewalld for sshd
  service: name=firewalld state=restarted
  when: sshd_ports.changed

- name: ensure host-specific ports are opened
  firewalld: port="{{ item }}/tcp" permanent=true state=enabled
  with_items: "{{ hostvars[inventory_hostname]['extra_ports'] | default([]) }}"
  register: extra_ports

- name: reload changes to firewalld
  service: name=firewalld state=restarted
  when: extra_ports.changed

- name: install epel
  yum: name=epel-release state=latest
  tags: 
    - packages

- name: install logwatch
  yum: name=logwatch state=latest
  tags: 
    - packages
  
# http://blog.iopsl.com/fail2ban-on-centos-7-to-protect-ssh/
- name: install fail2ban
  yum: name=fail2ban state=latest
  tags: 
    - packages

- name: install fail2ban systemd
  yum: name=fail2ban-systemd state=latest
  tags: 
    - packages
  
- name: install sshd configs for fail2 ban
  template: src=sshd.local.j2 dest=/etc/fail2ban/jail.d/sshd.local

- name: ensure fail2ban runs
  service: name=fail2ban state=restarted enabled=yes




