
### basic users stuff 

- group: name=gregf state=present gid=1000
   
- user: name=gregf state=present uid=1000 shell=/bin/bash group=gregf groups=admin append=yes
- authorized_key: user=gregf key="{{ lookup('file', '/home/gregf/.ssh/id_rsa.pub') }}"

### sudoers

- lineinfile: dest=/etc/sudoers state=absent regexp="^%wheel"
- lineinfile: dest=/etc/sudoers state=absent regexp="^gregf"

### firewalls

- name: ensure firewalld is started
  service: name=firewalld state=started enabled=yes

- name: configure firewall services / ports
  firewalld: service=ssh permanent=true state=enabled

- firewalld: service=http permanent=true state=enabled
- firewalld: service=https permanent=true state=enabled
- firewalld: port=8080/tcp permanent=true state=enabled
- firewalld: port=8090/tcp permanent=true state=enabled

- name: configure ssh hitcount / ban directives
  script: firewall.sh

- name: reload changes to firewalld
  service: name=firewalld state=restarted

