
- name: disable that pesky selinux
  selinux: state=disabled

- name: clean up sudoers
  lineinfile: dest=/etc/sudoers state=absent regexp="^%wheel"

- name: remove requiretty line from sudoers
  lineinfile: dest=/etc/sudoers state=absent regexp="^Defaults(.*)requiretty"

- name: ensure firewalld is started
  service: name=firewalld state=started enabled=yes
  tags:
    - firewall

- name: configure firewall services / ports
  firewalld: service=ssh permanent=true state=enabled immediate=true
  tags:
    - firewall

- name: ensure host-specific ports are opened
  firewalld: port="{{ item }}/tcp" permanent=true state=enabled immediate=true
  with_items: "{{ hostvars[inventory_hostname]['allowed_extra_ports'] | default([]) }}"
  tags: 
    - firewall

- name: ensure host-specific ports are closed
  firewalld: port="{{ item }}/tcp" permanent=true state=disabled immediate=true
  with_items: "{{ hostvars[inventory_hostname]['disallowed_extra_ports'] | default([]) }}"
  register: disallowed_extra_ports
  tags:
    - firewall

- name: ensure host-specific ports are closed
  firewalld: port="{{ item }}/udp" permanent=true state=disabled immediate=true
  with_items: "{{ hostvars[inventory_hostname]['disallowed_extra_ports'] | default([]) }}"
  register: disallowed_extra_udp_ports
  tags:
    - firewall

- name: install epel
  yum: name=epel-release state=latest
  tags: 
    - packages

- name: install logwatch
  yum: name=logwatch state=latest
  tags: 
    - packages
  
# http://blog.iopsl.com/fail2ban-on-centos-7-to-protect-ssh/
- name: install fail2ban
  yum: name=fail2ban state=latest
  tags: 
    - packages

- name: install fail2ban systemd
  yum: name=fail2ban-systemd state=latest
  tags: 
    - packages
  
- name: install sshd configs for fail2 ban
  template: src=sshd.local.j2 dest=/etc/fail2ban/jail.d/sshd.local

- name: ensure fail2ban runs
  service: name=fail2ban state=restarted enabled=yes




