
### basic users stuff 

- name: disable that pesky selinux
  selinux: state=disabled

- group: name={{user}} state=present gid=1000
   
- user: name={{user}} state=present uid=1000 shell=/bin/bash group={{user}} groups=admin append=yes
- authorized_key: user={{user}} key="{{ lookup('file', '/home/{{user}}/.ssh/id_rsa.pub') }}"

### sudoers

- lineinfile: dest=/etc/sudoers state=absent regexp="^%wheel"

### firewalls

- name: ensure firewalld is started
  service: name=firewalld state=started enabled=yes

- name: configure firewall services / ports
  firewalld: service=ssh permanent=true state=enabled

- firewalld: service=http permanent=true state=enabled
- firewalld: service=https permanent=true state=enabled
- firewalld: port=8080/tcp permanent=true state=enabled
- firewalld: port=8090/tcp permanent=true state=enabled

- name: reload changes to firewalld
  service: name=firewalld state=restarted

