
#
# we want to set up a client properly with mail... um,....
#
#
#

- name: ensure stuff
  yum: name={{ item }} state=latest update_cache=true
  with_items:
    - postgresql-pltcl
  tags:
    - packages

