
- name: upgrade all packages
  yum: name=* state=latest

- name: ensure networkmanager is deactivated
  service: name=NetworkManager state=stopped enabled=no
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: ensure epel
  yum: name=epel-release state=latest
  tags: 
    - packages

- name: install ius 
  yum: name=ius-release state=latest
  tags: 
    - packages

- name: ensure several packages are installed
  yum: name={{ item }} state=latest update_cache=true
  with_items:
    - epel-release
    - wget
    - zsh
    - git
    - git-core
    - emacs-nox
    - htop
    - python-pip
    - net-tools
  tags:
    - packages

- name: custom etc/issue
  template: src=issue.j2 dest=/etc/issue owner=root

### NTP

- name: be sure ntp is installed
  yum: pkg=ntp state=installed
  tags: ntp

- name: be sure ntp is configured
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntpd
  tags: ntp

- name: be sure ntpd is running and enabled
  service: name=ntpd state=running enabled=yes
  tags: ntp

### END NTP


