


- name: ensure nginx packages are installed
  yum: name=nginx state=latest

- name: ensure nginx service is enabled and running
  service: name=nginx enabled=yes state=started

- name: ensure nginx.conf installed
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: 
    - restart nginx

- name: ensure nginx/conf.d/default installed
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf
  notify:
    - restart nginx

- name: ensure php packages are installed
  yum: name=php state=latest

# TODO yum install php-mysqlnd

- name: ensure php.ini is installed
  template: src=php.ini.j2 dest=/etc/php.ini

- name: ensure php-fpm packages are installed
  yum: name=php-fpm state=latest

- name: ensure php-fpm.d/www.conf installed
  template: src=www.conf.j2 dest=/etc/php-fpm.d/www.conf
  notify: 
    - restart php-fpm

- name: ensure php-fpm service is enabled and running
  service: name=php-fpm enabled=yes state=started

- name: copy info.php over into htdocs for testing
  copy: src=info.php dest=/usr/share/nginx/html owner=root group=root


